on:
  pull_request_target:
    
jobs:
  myjob:
    runs-on: ubuntu-latest
         
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          
      - run: |
          echo ${{ secrets.TEST_FLAG }}
        
      - run: |
          npm install
          node index.js
